version: '3'
env:
  JAR_VERSION: '{{.JAR_VERSION | default "0.1"}}'
  CONTAINER_VERSION: '{{.CONTAINER_VERSION | default "0.1"}}'
  CONTAINER_IMAGE: '{{.CONTAINER_IMAGE | default "openapi-builder"}}'
  MOUNT_PATH: '{{.MOUNT_PATH | default "/openapi"}}'
  PORT: '{{.PORT | default "8080"}}'
  HOST: '{{.HOST | default "localhost"}}'

tasks:
  todo:
    vars:
      JSON: '{ "description": "Todo string", "title": "Todo string" }'
    cmds:
      - "curl -X POST 'http://{{.HOST}}:{{.PORT}}/todo' -H 'Content-Type: application/json' -d '{{.JSON}}'"

  list:
    cmds:
      - "curl -X GET 'http://{{.HOST}}:{{.PORT}}/todo' -H 'accept: */*' | jq ."

  refresh-api:
    internal: true
    cmds:
      - "curl -X GET 'http://{{.HOST}}:{{.PORT}}/api.json' -H 'accept: */*' -o openapi.json"
    sources:
      - todo-service/target/todo-service-{{.JAR_VERSION}}-jar-with-dependencies.jar
    generates:
      - openapi.json

  api:
    deps: [refresh-api]
    cmds:
      - cat openapi.json | jq .

  test:
    cmds:
      - hurl --test todo.hurl

  build:
    cmds:
      - mvn package
    sources:
      - todo-service/src/main/kotlin/**/*.kt
    generates:
      - todo-service/target/todo-service-{{.JAR_VERSION}}-jar-with-dependencies.jar

  run:
    cmds:
      - java -jar todo-service/target/todo-service-{{.JAR_VERSION}}-jar-with-dependencies.jar

  clean:
    cmds:
      - mvn clean
      - rm -rf src/site/asciidoc/generated

  generate:
    cmds:
      - |
        podman run --rm -v .:{{.MOUNT_PATH}} \
          -it docker.io/openapitools/openapi-generator-cli generate -g asciidoc \
          -i {{.MOUNT_PATH}}/openapi.json -o {{.MOUNT_PATH}}/asciidoc/src/site/asciidoc/generated
    sources:
      - openapi.json
    generates:
      - asciidoc/src/site/asciidoc/generated/index.adoc

  asciidoc:
    deps: [generate]
    cmds:
      - mvn -f asciidoc/pom.xml -P generate-docs generate-resources
    sources:
      - asciidoc/src/site/asciidoc/index.adoc
    generates:
      - asciidoc/target/static/documentation/index.html

  open:
    deps: [asciidoc]
    cmds:
      - xdg-open asciidoc/target/static/documentation/index.html
    sources:
      - openapi.json
    generates:
      - xdg-open asciidoc/target/static/documentation/index.html

  publish:
    cmds:
      - |
        podman run --rm --dns 8.8.8.8 -v .:{{.MOUNT_PATH}} \
            -it docker.io/unexist/asciidoxy-builder:$(VERSION) \
            -e CONFLUENCE_URL \
            -e CONFLUENCE_SPACE_KEY \
            -e CONFLUENCE_ANCESTOR_ID \
            -e CONFLUENCE_USER \
            -e CONFLUENCE_TOKEN \
            sh -c "cd $(MOUNT_PATH) && mvn -f pom.xml -P generate-docs-and-publish generate-resources"
